language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - ruby-head
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rubocop
  - bundle exec rspec
